"""initial_schema

Revision ID: 708d1432f72e
Revises: 
Create Date: 2026-06-01 16:10:51.587102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '708d1432f72e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_providers_user_id'), 'auth_providers', ['user_id'], unique=False)
    op.create_table('image_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_image_id', sa.Uuid(), nullable=True),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('storage_provider', sa.String(length=16), nullable=False),
    sa.Column('bucket', sa.String(length=128), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('exif_json', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_image_id'], ['image_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket', 'object_key', name='uq_bucket_object_key')
    )
    op.create_table('analysis_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_tasks_status_created', 'analysis_tasks', ['status', 'created_at'], unique=False)
    op.create_index('idx_analysis_tasks_user_created', 'analysis_tasks', ['user_id', 'created_at'], unique=False)
    op.create_table('analysis_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('feature_json', postgresql.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('idx_analysis_features_feature_json_gin', 'analysis_features', ['feature_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_analysis_features_image_created', 'analysis_features', ['image_id', 'created_at'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('result_json', postgresql.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('idx_analysis_results_image_created', 'analysis_results', ['image_id', 'created_at'], unique=False)
    op.create_index('idx_analysis_results_result_json_gin', 'analysis_results', ['result_json'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_analysis_results_result_json_gin', table_name='analysis_results', postgresql_using='gin')
    op.drop_index('idx_analysis_results_image_created', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index('idx_analysis_features_image_created', table_name='analysis_features')
    op.drop_index('idx_analysis_features_feature_json_gin', table_name='analysis_features', postgresql_using='gin')
    op.drop_table('analysis_features')
    op.drop_index('idx_analysis_tasks_user_created', table_name='analysis_tasks')
    op.drop_index('idx_analysis_tasks_status_created', table_name='analysis_tasks')
    op.drop_table('analysis_tasks')
    op.drop_table('image_assets')
    op.drop_index(op.f('ix_auth_providers_user_id'), table_name='auth_providers')
    op.drop_table('auth_providers')
    op.drop_table('users')
    # ### end Alembic commands ###
